#!/usr/bin/env python3

import sys
import shutil
import os

if len(sys.argv) != 2:
    print("Usage: run-test [setup|teardown]")
    sys.exit(1)

subcommand = sys.argv[1]

if subcommand == "setup":
    if os.path.exists("test"):
        shutil.rmtree("test")
    os.makedirs("test/edu/bvu/cs")
    with open("test/edu/bvu/cs/DevOps.java", "w") as f:
        f.write('// DevOps.java\npublic class DevOps {\n    public DevOps() {\n    }\n}')
    with open("test/edu/bvu/cs/DevOpsMain.java", "w") as f:
        f.write('// DevOpsMain.java\npublic class DevOpsMain {\n    public static void main(String[] args) {\n        DevOps dev = new DevOps();\n    }\n}')
elif subcommand == "teardown":
    if not os.path.exists("test"):
        print("Warning: test directory does not exist")
    else:
        shutil.rmtree("test")
else:
    print("Usage: run-test [setup|teardown]")
    sys.exit(1)

